# Form implementation generated from reading ui file 'f:\Ain Shams\Spring 2022\Assignments\Assignments - CSE439 - Design of Compilers\CSE439Team3Spring22\MainGUI.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 821, 621))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.489474, y1:1, x2:0.473684, y2:0, stop:0 rgba(6, 96, 159, 211), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.widget.setObjectName("widget")
        self.welcomeLabel = QtWidgets.QLabel(self.widget)
        self.welcomeLabel.setGeometry(QtCore.QRect(190, 190, 431, 91))
        self.welcomeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 30pt \"Georgia\";")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.logoLabel = QtWidgets.QLabel(self.widget)
        self.logoLabel.setGeometry(QtCore.QRect(310, 10, 171, 171))
        self.logoLabel.setStyleSheet("")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("f:\\Ain Shams\\Spring 2022\\Assignments\\Assignments - CSE439 - Design of Compilers\\CSE439Team3Spring22\\res/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.scannerPushButton = QtWidgets.QPushButton(self.widget)
        self.scannerPushButton.setGeometry(QtCore.QRect(100, 440, 261, 101))
        self.scannerPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.scannerPushButton.setStyleSheet("font: 75 20pt \"Georgia\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:35px;\n"
"color: rgb(6, 96, 159)")
        self.scannerPushButton.setObjectName("scannerPushButton")
        self.parserPushButton = QtWidgets.QPushButton(self.widget)
        self.parserPushButton.setGeometry(QtCore.QRect(450, 440, 261, 101))
        self.parserPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.parserPushButton.setStyleSheet("font: 75 20pt \"Georgia\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:35px;\n"
"color: rgb(6, 96, 159)")
        self.parserPushButton.setObjectName("parserPushButton")
        self.welcomeLabel_2 = QtWidgets.QLabel(self.widget)
        self.welcomeLabel_2.setGeometry(QtCore.QRect(190, 290, 431, 91))
        self.welcomeLabel_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 30pt \"Georgia\";")
        self.welcomeLabel_2.setObjectName("welcomeLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:normal;\">Welcome to</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:normal;\">CSE439 Group 3 Project</span></p></body></html>"))
        self.scannerPushButton.setText(_translate("MainWindow", "Scanner"))
        self.parserPushButton.setText(_translate("MainWindow", "Parser"))
        self.welcomeLabel_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; font-style:normal;\">TINY Language Compiler</span></p></body></html>"))
