# Form implementation generated from reading ui file 'f:\Ain Shams\Spring 2022\Assignments\Assignments - CSE439 - Design of Compilers\CSE439Team3Spring22\MainGUI - Copy.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 821, 621))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.welcomeLabel = QtWidgets.QLabel(self.widget)
        self.welcomeLabel.setGeometry(QtCore.QRect(190, 180, 431, 111))
        self.welcomeLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 30pt \"Georgia\";")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.logoLabel = QtWidgets.QLabel(self.widget)
        self.logoLabel.setGeometry(QtCore.QRect(310, 10, 171, 171))
        self.logoLabel.setStyleSheet("")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("f:\\Ain Shams\\Spring 2022\\Assignments\\Assignments - CSE439 - Design of Compilers\\CSE439Team3Spring22\\res/logo.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setObjectName("logoLabel")
        self.scannerPushButton = QtWidgets.QPushButton(self.widget)
        self.scannerPushButton.setGeometry(QtCore.QRect(100, 440, 261, 101))
        self.scannerPushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Cambria\";\n"
"background-color:rgb(7, 119, 197);\n"
"border-radius:35px;\n"
"font: 75 24pt \"Georgia\";\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("f:\\Ain Shams\\Spring 2022\\Assignments\\Assignments - CSE439 - Design of Compilers\\CSE439Team3Spring22\\res/goto.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.scannerPushButton.setIcon(icon1)
        self.scannerPushButton.setIconSize(QtCore.QSize(40, 40))
        self.scannerPushButton.setObjectName("scannerPushButton")
        self.parserPushButton = QtWidgets.QPushButton(self.widget)
        self.parserPushButton.setGeometry(QtCore.QRect(450, 440, 261, 101))
        self.parserPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.parserPushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Cambria\";\n"
"background-color:rgb(7, 119, 197);\n"
"border-radius:35px;\n"
"font: 75 24pt \"Georgia\";\n"
"")
        self.parserPushButton.setIcon(icon1)
        self.parserPushButton.setIconSize(QtCore.QSize(40, 40))
        self.parserPushButton.setObjectName("parserPushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSE439 Group 3 Project"))
        self.welcomeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:normal; color:#06609f;\">Welcome to</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:normal; color:#06609f;\">CSE439 Group 3 Project</span></p></body></html>"))
        self.scannerPushButton.setText(_translate("MainWindow", "Scanner"))
        self.parserPushButton.setText(_translate("MainWindow", "Parser"))
