# Form implementation generated from reading ui file 'f:\Ain Shams\Spring 2022\Assignments\Assignments - CSE439 - Design of Compilers\CSE439Team3Spring22\ui\TableDialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1066, 686)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\Ain Shams\\Spring 2022\\Assignments\\Assignments - CSE439 - Design of Compilers\\CSE439Team3Spring22\\ui\\logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.parsingTableLabel = QtWidgets.QLabel(Dialog)
        self.parsingTableLabel.setGeometry(QtCore.QRect(20, 50, 1031, 551))
        self.parsingTableLabel.setText("")
        self.parsingTableLabel.setPixmap(QtGui.QPixmap("f:\\Ain Shams\\Spring 2022\\Assignments\\Assignments - CSE439 - Design of Compilers\\CSE439Team3Spring22\\ui\\res/parsingtable.png"))
        self.parsingTableLabel.setScaledContents(True)
        self.parsingTableLabel.setObjectName("parsingTableLabel")
        self.insertCodeLabel = QtWidgets.QLabel(Dialog)
        self.insertCodeLabel.setGeometry(QtCore.QRect(30, 10, 341, 41))
        self.insertCodeLabel.setStyleSheet("color: rgb(6, 96, 159);\n"
"font: 75 16pt \"Georgia\";")
        self.insertCodeLabel.setObjectName("insertCodeLabel")
        self.okPushButton = QtWidgets.QPushButton(Dialog)
        self.okPushButton.setGeometry(QtCore.QRect(490, 630, 93, 28))
        self.okPushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.okPushButton.setObjectName("okPushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parsing Table"))
        self.insertCodeLabel.setText(_translate("Dialog", "<html><head/><body><p>SLR(1) Parsing Table:</p></body></html>"))
        self.okPushButton.setText(_translate("Dialog", "OK"))
